export const MEMBERS: Record<string, { member: string; party: 'D' | 'R' | 'I'; state: string; district: string }> = {
  '0101': { member: 'Barry Moore', party: 'R', state: 'Alabama', district: '01' },
  '0102': { member: 'Shomari Figures', party: 'D', state: 'Alabama', district: '02' },
  '0103': { member: 'Mike Rogers', party: 'R', state: 'Alabama', district: '03' },
  '0104': { member: 'Robert Aderholt', party: 'R', state: 'Alabama', district: '04' },
  '0105': { member: 'Dale Strong', party: 'R', state: 'Alabama', district: '05' },
  '0106': { member: 'Gary Palmer', party: 'R', state: 'Alabama', district: '06' },
  '0107': { member: 'Terri Sewell', party: 'D', state: 'Alabama', district: '07' },
  '0200': { member: 'Nicholas Begich', party: 'R', state: 'Alaska', district: '00' },
  '0401': { member: 'David Schweikert', party: 'R', state: 'Arizona', district: '01' },
  '0402': { member: 'Elijah Crane', party: 'R', state: 'Arizona', district: '02' },
  '0403': { member: 'Yassamin Ansari', party: 'D', state: 'Arizona', district: '03' },
  '0404': { member: 'Greg Stanton', party: 'D', state: 'Arizona', district: '04' },
  '0405': { member: 'Andy Biggs', party: 'R', state: 'Arizona', district: '05' },
  '0406': { member: 'Juan Ciscomani', party: 'R', state: 'Arizona', district: '06' },
  '0407': { member: 'Vacant', party: 'I', state: 'Arizona', district: '07' },
  '0408': { member: 'Abraham Hamadeh', party: 'R', state: 'Arizona', district: '08' },
  '0409': { member: 'Paul Gosar', party: 'R', state: 'Arizona', district: '09' },
  '0501': { member: 'Eric Crawford', party: 'R', state: 'Arkansas', district: '01' },
  '0502': { member: 'J. Hill', party: 'R', state: 'Arkansas', district: '02' },
  '0503': { member: 'Steve Womack', party: 'R', state: 'Arkansas', district: '03' },
  '0504': { member: 'Bruce Westerman', party: 'R', state: 'Arkansas', district: '04' },
  '0601': { member: 'Doug LaMalfa', party: 'R', state: 'California', district: '01' },
  '0602': { member: 'Jared Huffman', party: 'D', state: 'California', district: '02' },
  '0603': { member: 'Kevin Kiley', party: 'R', state: 'California', district: '03' },
  '0604': { member: 'Mike Thompson', party: 'D', state: 'California', district: '04' },
  '0605': { member: 'Tom McClintock', party: 'R', state: 'California', district: '05' },
  '0606': { member: 'Ami Bera', party: 'D', state: 'California', district: '06' },
  '0607': { member: 'Doris Matsui', party: 'D', state: 'California', district: '07' },
  '0608': { member: 'John Garamendi', party: 'D', state: 'California', district: '08' },
  '0609': { member: 'Josh Harder', party: 'D', state: 'California', district: '09' },
  '0610': { member: 'Mark DeSaulnier', party: 'D', state: 'California', district: '10' },
  '0611': { member: 'Nancy Pelosi', party: 'D', state: 'California', district: '11' },
  '0612': { member: 'Lateefah Simon', party: 'D', state: 'California', district: '12' },
  '0613': { member: 'Adam Gray', party: 'D', state: 'California', district: '13' },
  '0614': { member: 'Eric Swalwell', party: 'D', state: 'California', district: '14' },
  '0615': { member: 'Kevin Mullin', party: 'D', state: 'California', district: '15' },
  '0616': { member: 'Sam Liccardo', party: 'D', state: 'California', district: '16' },
  '0617': { member: 'Ro Khanna', party: 'D', state: 'California', district: '17' },
  '0618': { member: 'Zoe Lofgren', party: 'D', state: 'California', district: '18' },
  '0619': { member: 'Jimmy Panetta', party: 'D', state: 'California', district: '19' },
  '0620': { member: 'Vince Fong', party: 'R', state: 'California', district: '20' },
  '0621': { member: 'Jim Costa', party: 'D', state: 'California', district: '21' },
  '0622': { member: 'David Valadao', party: 'R', state: 'California', district: '22' },
  '0623': { member: 'Jay Obernolte', party: 'R', state: 'California', district: '23' },
  '0624': { member: 'Salud Carbajal', party: 'D', state: 'California', district: '24' },
  '0625': { member: 'Raul Ruiz', party: 'D', state: 'California', district: '25' },
  '0626': { member: 'Julia Brownley', party: 'D', state: 'California', district: '26' },
  '0627': { member: 'George Whitesides', party: 'D', state: 'California', district: '27' },
  '0628': { member: 'Judy Chu', party: 'D', state: 'California', district: '28' },
  '0629': { member: 'Luz Rivas', party: 'D', state: 'California', district: '29' },
  '0630': { member: 'Laura Friedman', party: 'D', state: 'California', district: '30' },
  '0631': { member: 'Gilbert Cisneros', party: 'D', state: 'California', district: '31' },
  '0632': { member: 'Brad Sherman', party: 'D', state: 'California', district: '32' },
  '0633': { member: 'Pete Aguilar', party: 'D', state: 'California', district: '33' },
  '0634': { member: 'Jimmy Gomez', party: 'D', state: 'California', district: '34' },
  '0635': { member: 'Norma Torres', party: 'D', state: 'California', district: '35' },
  '0636': { member: 'Ted Lieu', party: 'D', state: 'California', district: '36' },
  '0637': { member: 'Sydney Kamlager-Dove', party: 'D', state: 'California', district: '37' },
  '0638': { member: 'Linda Sanchez', party: 'D', state: 'California', district: '38' },
  '0639': { member: 'Mark Takano', party: 'D', state: 'California', district: '39' },
  '0640': { member: 'Young Kim', party: 'R', state: 'California', district: '40' },
  '0641': { member: 'Ken Calvert', party: 'R', state: 'California', district: '41' },
  '0642': { member: 'Robert Garcia', party: 'D', state: 'California', district: '42' },
  '0643': { member: 'Maxine Waters', party: 'D', state: 'California', district: '43' },
  '0644': { member: 'Nanette Barragan', party: 'D', state: 'California', district: '44' },
  '0645': { member: 'Derek Tran', party: 'D', state: 'California', district: '45' },
  '0646': { member: 'J. Correa', party: 'D', state: 'California', district: '46' },
  '0647': { member: 'Dave Min', party: 'D', state: 'California', district: '47' },
  '0648': { member: 'Darrell Issa', party: 'R', state: 'California', district: '48' },
  '0649': { member: 'Mike Levin', party: 'D', state: 'California', district: '49' },
  '0650': { member: 'Scott Peters', party: 'D', state: 'California', district: '50' },
  '0651': { member: 'Sara Jacobs', party: 'D', state: 'California', district: '51' },
  '0652': { member: 'Juan Vargas', party: 'D', state: 'California', district: '52' },
  '0801': { member: 'Diana DeGette', party: 'D', state: 'Colorado', district: '01' },
  '0802': { member: 'Joe Neguse', party: 'D', state: 'Colorado', district: '02' },
  '0803': { member: 'Jeff Hurd', party: 'R', state: 'Colorado', district: '03' },
  '0804': { member: 'Lauren Boebert', party: 'R', state: 'Colorado', district: '04' },
  '0805': { member: 'Jeff Crank', party: 'R', state: 'Colorado', district: '05' },
  '0806': { member: 'Jason Crow', party: 'D', state: 'Colorado', district: '06' },
  '0807': { member: 'Brittany Pettersen', party: 'D', state: 'Colorado', district: '07' },
  '0808': { member: 'Gabe Evans', party: 'R', state: 'Colorado', district: '08' },
  '0901': { member: 'John Larson', party: 'D', state: 'Connecticut', district: '01' },
  '0902': { member: 'Joe Courtney', party: 'D', state: 'Connecticut', district: '02' },
  '0903': { member: 'Rosa DeLauro', party: 'D', state: 'Connecticut', district: '03' },
  '0904': { member: 'James Himes', party: 'D', state: 'Connecticut', district: '04' },
  '0905': { member: 'Jahana Hayes', party: 'D', state: 'Connecticut', district: '05' },
  '1000': { member: 'Sarah McBride', party: 'D', state: 'Delaware', district: '00' },
  '1198': { member: 'Eleanor Norton', party: 'D', state: 'District of Columbia', district: '98' },
  '1201': { member: 'Jimmy Patronis', party: 'R', state: 'Florida', district: '01' },
  '1202': { member: 'Neal Dunn', party: 'R', state: 'Florida', district: '02' },
  '1203': { member: 'Kat Cammack', party: 'R', state: 'Florida', district: '03' },
  '1204': { member: 'Aaron Bean', party: 'R', state: 'Florida', district: '04' },
  '1205': { member: 'John Rutherford', party: 'R', state: 'Florida', district: '05' },
  '1206': { member: 'Randy Fine', party: 'R', state: 'Florida', district: '06' },
  '1207': { member: 'Cory Mills', party: 'R', state: 'Florida', district: '07' },
  '1208': { member: 'Mike Haridopolos', party: 'R', state: 'Florida', district: '08' },
  '1209': { member: 'Darren Soto', party: 'D', state: 'Florida', district: '09' },
  '1210': { member: 'Maxwell Frost', party: 'D', state: 'Florida', district: '10' },
  '1211': { member: 'Daniel Webster', party: 'R', state: 'Florida', district: '11' },
  '1212': { member: 'Gus Bilirakis', party: 'R', state: 'Florida', district: '12' },
  '1213': { member: 'Anna Paulina Luna', party: 'R', state: 'Florida', district: '13' },
  '1214': { member: 'Kathy Castor', party: 'D', state: 'Florida', district: '14' },
  '1215': { member: 'Laurel Lee', party: 'R', state: 'Florida', district: '15' },
  '1216': { member: 'Vern Buchanan', party: 'R', state: 'Florida', district: '16' },
  '1217': { member: 'W. Steube', party: 'R', state: 'Florida', district: '17' },
  '1218': { member: 'Scott Franklin', party: 'R', state: 'Florida', district: '18' },
  '1219': { member: 'Byron Donalds', party: 'R', state: 'Florida', district: '19' },
  '1220': { member: 'Sheila Cherfilus-McCormick', party: 'D', state: 'Florida', district: '20' },
  '1221': { member: 'Brian Mast', party: 'R', state: 'Florida', district: '21' },
  '1222': { member: 'Lois Frankel', party: 'D', state: 'Florida', district: '22' },
  '1223': { member: 'Jared Moskowitz', party: 'D', state: 'Florida', district: '23' },
  '1224': { member: 'Frederica Wilson', party: 'D', state: 'Florida', district: '24' },
  '1225': { member: 'Debbie Wasserman Schultz', party: 'D', state: 'Florida', district: '25' },
  '1226': { member: 'Mario Diaz-Balart', party: 'R', state: 'Florida', district: '26' },
  '1227': { member: 'Maria Salazar', party: 'R', state: 'Florida', district: '27' },
  '1228': { member: 'Carlos Gimenez', party: 'R', state: 'Florida', district: '28' },
  '1301': { member: 'Earl Carter', party: 'R', state: 'Georgia', district: '01' },
  '1302': { member: 'Sanford Bishop', party: 'D', state: 'Georgia', district: '02' },
  '1303': { member: 'Brian Jack', party: 'R', state: 'Georgia', district: '03' },
  '1304': { member: 'Henry Johnson', party: 'D', state: 'Georgia', district: '04' },
  '1305': { member: 'Nikema Williams', party: 'D', state: 'Georgia', district: '05' },
  '1306': { member: 'Lucy McBath', party: 'D', state: 'Georgia', district: '06' },
  '1307': { member: 'Richard McCormick', party: 'R', state: 'Georgia', district: '07' },
  '1308': { member: 'Austin Scott', party: 'R', state: 'Georgia', district: '08' },
  '1309': { member: 'Andrew Clyde', party: 'R', state: 'Georgia', district: '09' },
  '1310': { member: 'Mike Collins', party: 'R', state: 'Georgia', district: '10' },
  '1311': { member: 'Barry Loudermilk', party: 'R', state: 'Georgia', district: '11' },
  '1312': { member: 'Rick Allen', party: 'R', state: 'Georgia', district: '12' },
  '1313': { member: 'David Scott', party: 'D', state: 'Georgia', district: '13' },
  '1314': { member: 'Marjorie Greene', party: 'R', state: 'Georgia', district: '14' },
  '1501': { member: 'Ed Case', party: 'D', state: 'Hawaii', district: '01' },
  '1502': { member: 'Jill Tokuda', party: 'D', state: 'Hawaii', district: '02' },
  '1601': { member: 'Russ Fulcher', party: 'R', state: 'Idaho', district: '01' },
  '1602': { member: 'Michael Simpson', party: 'R', state: 'Idaho', district: '02' },
  '1701': { member: 'Jonathan Jackson', party: 'D', state: 'Illinois', district: '01' },
  '1702': { member: 'Robin Kelly', party: 'D', state: 'Illinois', district: '02' },
  '1703': { member: 'Delia Ramirez', party: 'D', state: 'Illinois', district: '03' },
  '1704': { member: 'Jesus Garcia', party: 'D', state: 'Illinois', district: '04' },
  '1705': { member: 'Mike Quigley', party: 'D', state: 'Illinois', district: '05' },
  '1706': { member: 'Sean Casten', party: 'D', state: 'Illinois', district: '06' },
  '1707': { member: 'Danny Davis', party: 'D', state: 'Illinois', district: '07' },
  '1708': { member: 'Raja Krishnamoorthi', party: 'D', state: 'Illinois', district: '08' },
  '1709': { member: 'Janice Schakowsky', party: 'D', state: 'Illinois', district: '09' },
  '1710': { member: 'Bradley Schneider', party: 'D', state: 'Illinois', district: '10' },
  '1711': { member: 'Bill Foster', party: 'D', state: 'Illinois', district: '11' },
  '1712': { member: 'Mike Bost', party: 'R', state: 'Illinois', district: '12' },
  '1713': { member: 'Nikki Budzinski', party: 'D', state: 'Illinois', district: '13' },
  '1714': { member: 'Lauren Underwood', party: 'D', state: 'Illinois', district: '14' },
  '1715': { member: 'Mary Miller', party: 'R', state: 'Illinois', district: '15' },
  '1716': { member: 'Darin LaHood', party: 'R', state: 'Illinois', district: '16' },
  '1717': { member: 'Eric Sorensen', party: 'D', state: 'Illinois', district: '17' },
  '1801': { member: 'Frank Mrvan', party: 'D', state: 'Indiana', district: '01' },
  '1802': { member: 'Rudy Yakym', party: 'R', state: 'Indiana', district: '02' },
  '1803': { member: 'Marlin Stutzman', party: 'R', state: 'Indiana', district: '03' },
  '1804': { member: 'James Baird', party: 'R', state: 'Indiana', district: '04' },
  '1805': { member: 'Victoria Spartz', party: 'R', state: 'Indiana', district: '05' },
  '1806': { member: 'Jefferson Shreve', party: 'R', state: 'Indiana', district: '06' },
  '1807': { member: 'Andre Carson', party: 'D', state: 'Indiana', district: '07' },
  '1808': { member: 'Mark Messmer', party: 'R', state: 'Indiana', district: '08' },
  '1809': { member: 'Erin Houchin', party: 'R', state: 'Indiana', district: '09' },
  '1901': { member: 'Mariannette Miller-Meeks', party: 'R', state: 'Iowa', district: '01' },
  '1902': { member: 'Ashley Hinson', party: 'R', state: 'Iowa', district: '02' },
  '1903': { member: 'Zachary Nunn', party: 'R', state: 'Iowa', district: '03' },
  '1904': { member: 'Randy Feenstra', party: 'R', state: 'Iowa', district: '04' },
  '2001': { member: 'Tracey Mann', party: 'R', state: 'Kansas', district: '01' },
  '2002': { member: 'Derek Schmidt', party: 'R', state: 'Kansas', district: '02' },
  '2003': { member: 'Sharice Davids', party: 'D', state: 'Kansas', district: '03' },
  '2004': { member: 'Ron Estes', party: 'R', state: 'Kansas', district: '04' },
  '2101': { member: 'James Comer', party: 'R', state: 'Kentucky', district: '01' },
  '2102': { member: 'Brett Guthrie', party: 'R', state: 'Kentucky', district: '02' },
  '2103': { member: 'Morgan McGarvey', party: 'D', state: 'Kentucky', district: '03' },
  '2104': { member: 'Thomas Massie', party: 'R', state: 'Kentucky', district: '04' },
  '2105': { member: 'Harold Rogers', party: 'R', state: 'Kentucky', district: '05' },
  '2106': { member: 'Andy Barr', party: 'R', state: 'Kentucky', district: '06' },
  '2201': { member: 'Steve Scalise', party: 'R', state: 'Louisiana', district: '01' },
  '2202': { member: 'Troy Carter', party: 'D', state: 'Louisiana', district: '02' },
  '2203': { member: 'Clay Higgins', party: 'R', state: 'Louisiana', district: '03' },
  '2204': { member: 'Mike Johnson', party: 'R', state: 'Louisiana', district: '04' },
  '2205': { member: 'Julia Letlow', party: 'R', state: 'Louisiana', district: '05' },
  '2206': { member: 'Cleo Fields', party: 'D', state: 'Louisiana', district: '06' },
  '2301': { member: 'Chellie Pingree', party: 'D', state: 'Maine', district: '01' },
  '2302': { member: 'Jared Golden', party: 'D', state: 'Maine', district: '02' },
  '2401': { member: 'Andy Harris', party: 'R', state: 'Maryland', district: '01' },
  '2402': { member: 'Johnny Olszewski', party: 'D', state: 'Maryland', district: '02' },
  '2403': { member: 'Sarah Elfreth', party: 'D', state: 'Maryland', district: '03' },
  '2404': { member: 'Glenn Ivey', party: 'D', state: 'Maryland', district: '04' },
  '2405': { member: 'Steny Hoyer', party: 'D', state: 'Maryland', district: '05' },
  '2406': { member: 'April McClain Delaney', party: 'D', state: 'Maryland', district: '06' },
  '2407': { member: 'Kweisi Mfume', party: 'D', state: 'Maryland', district: '07' },
  '2408': { member: 'Jamie Raskin', party: 'D', state: 'Maryland', district: '08' },
  '2501': { member: 'Richard Neal', party: 'D', state: 'Massachusetts', district: '01' },
  '2502': { member: 'James McGovern', party: 'D', state: 'Massachusetts', district: '02' },
  '2503': { member: 'Lori Trahan', party: 'D', state: 'Massachusetts', district: '03' },
  '2504': { member: 'Jake Auchincloss', party: 'D', state: 'Massachusetts', district: '04' },
  '2505': { member: 'Katherine Clark', party: 'D', state: 'Massachusetts', district: '05' },
  '2506': { member: 'Seth Moulton', party: 'D', state: 'Massachusetts', district: '06' },
  '2507': { member: 'Ayanna Pressley', party: 'D', state: 'Massachusetts', district: '07' },
  '2508': { member: 'Stephen Lynch', party: 'D', state: 'Massachusetts', district: '08' },
  '2509': { member: 'William Keating', party: 'D', state: 'Massachusetts', district: '09' },
  '2601': { member: 'Jack Bergman', party: 'R', state: 'Michigan', district: '01' },
  '2602': { member: 'John Moolenaar', party: 'R', state: 'Michigan', district: '02' },
  '2603': { member: 'Hillary Scholten', party: 'D', state: 'Michigan', district: '03' },
  '2604': { member: 'Bill Huizenga', party: 'R', state: 'Michigan', district: '04' },
  '2605': { member: 'Tim Walberg', party: 'R', state: 'Michigan', district: '05' },
  '2606': { member: 'Debbie Dingell', party: 'D', state: 'Michigan', district: '06' },
  '2607': { member: 'Tom Barrett', party: 'R', state: 'Michigan', district: '07' },
  '2608': { member: 'Kristen McDonald Rivet', party: 'D', state: 'Michigan', district: '08' },
  '2609': { member: 'Lisa McClain', party: 'R', state: 'Michigan', district: '09' },
  '2610': { member: 'John James', party: 'R', state: 'Michigan', district: '10' },
  '2611': { member: 'Haley Stevens', party: 'D', state: 'Michigan', district: '11' },
  '2612': { member: 'Rashida Tlaib', party: 'D', state: 'Michigan', district: '12' },
  '2613': { member: 'Shri Thanedar', party: 'D', state: 'Michigan', district: '13' },
  '2701': { member: 'Brad Finstad', party: 'R', state: 'Minnesota', district: '01' },
  '2702': { member: 'Angie Craig', party: 'D', state: 'Minnesota', district: '02' },
  '2703': { member: 'Kelly Morrison', party: 'D', state: 'Minnesota', district: '03' },
  '2704': { member: 'Betty McCollum', party: 'D', state: 'Minnesota', district: '04' },
  '2705': { member: 'Ilhan Omar', party: 'D', state: 'Minnesota', district: '05' },
  '2706': { member: 'Tom Emmer', party: 'R', state: 'Minnesota', district: '06' },
  '2707': { member: 'Michelle Fischbach', party: 'R', state: 'Minnesota', district: '07' },
  '2708': { member: 'Pete Stauber', party: 'R', state: 'Minnesota', district: '08' },
  '2801': { member: 'Trent Kelly', party: 'R', state: 'Mississippi', district: '01' },
  '2802': { member: 'Bennie Thompson', party: 'D', state: 'Mississippi', district: '02' },
  '2803': { member: 'Michael Guest', party: 'R', state: 'Mississippi', district: '03' },
  '2804': { member: 'Mike Ezell', party: 'R', state: 'Mississippi', district: '04' },
  '2901': { member: 'Wesley Bell', party: 'D', state: 'Missouri', district: '01' },
  '2902': { member: 'Ann Wagner', party: 'R', state: 'Missouri', district: '02' },
  '2903': { member: 'Robert Onder', party: 'R', state: 'Missouri', district: '03' },
  '2904': { member: 'Mark Alford', party: 'R', state: 'Missouri', district: '04' },
  '2905': { member: 'Emanuel Cleaver', party: 'D', state: 'Missouri', district: '05' },
  '2906': { member: 'Sam Graves', party: 'R', state: 'Missouri', district: '06' },
  '2907': { member: 'Eric Burlison', party: 'R', state: 'Missouri', district: '07' },
  '2908': { member: 'Jason Smith', party: 'R', state: 'Missouri', district: '08' },
  '3001': { member: 'Ryan Zinke', party: 'R', state: 'Montana', district: '01' },
  '3002': { member: 'Troy Downing', party: 'R', state: 'Montana', district: '02' },
  '3101': { member: 'Mike Flood', party: 'R', state: 'Nebraska', district: '01' },
  '3102': { member: 'Don Bacon', party: 'R', state: 'Nebraska', district: '02' },
  '3103': { member: 'Adrian Smith', party: 'R', state: 'Nebraska', district: '03' },
  '3201': { member: 'Dina Titus', party: 'D', state: 'Nevada', district: '01' },
  '3202': { member: 'Mark Amodei', party: 'R', state: 'Nevada', district: '02' },
  '3203': { member: 'Susie Lee', party: 'D', state: 'Nevada', district: '03' },
  '3204': { member: 'Steven Horsford', party: 'D', state: 'Nevada', district: '04' },
  '3301': { member: 'Chris Pappas', party: 'D', state: 'New Hampshire', district: '01' },
  '3302': { member: 'Maggie Goodlander', party: 'D', state: 'New Hampshire', district: '02' },
  '3401': { member: 'Donald Norcross', party: 'D', state: 'New Jersey', district: '01' },
  '3402': { member: 'Jefferson Van Drew', party: 'R', state: 'New Jersey', district: '02' },
  '3403': { member: 'Herbert Conaway', party: 'D', state: 'New Jersey', district: '03' },
  '3404': { member: 'Christopher Smith', party: 'R', state: 'New Jersey', district: '04' },
  '3405': { member: 'Josh Gottheimer', party: 'D', state: 'New Jersey', district: '05' },
  '3406': { member: 'Frank Pallone', party: 'D', state: 'New Jersey', district: '06' },
  '3407': { member: 'Thomas Kean', party: 'R', state: 'New Jersey', district: '07' },
  '3408': { member: 'Robert Menendez', party: 'D', state: 'New Jersey', district: '08' },
  '3409': { member: 'Nellie Pou', party: 'D', state: 'New Jersey', district: '09' },
  '3410': { member: 'LaMonica McIver', party: 'D', state: 'New Jersey', district: '10' },
  '3411': { member: 'Mikie Sherrill', party: 'D', state: 'New Jersey', district: '11' },
  '3412': { member: 'Bonnie Watson Coleman', party: 'D', state: 'New Jersey', district: '12' },
  '3501': { member: 'Melanie Stansbury', party: 'D', state: 'New Mexico', district: '01' },
  '3502': { member: 'Gabe Vasquez', party: 'D', state: 'New Mexico', district: '02' },
  '3503': { member: 'Teresa Leger Fernandez', party: 'D', state: 'New Mexico', district: '03' },
  '3601': { member: 'Nick LaLota', party: 'R', state: 'New York', district: '01' },
  '3602': { member: 'Andrew Garbarino', party: 'R', state: 'New York', district: '02' },
  '3603': { member: 'Thomas Suozzi', party: 'D', state: 'New York', district: '03' },
  '3604': { member: 'Laura Gillen', party: 'D', state: 'New York', district: '04' },
  '3605': { member: 'Gregory Meeks', party: 'D', state: 'New York', district: '05' },
  '3606': { member: 'Grace Meng', party: 'D', state: 'New York', district: '06' },
  '3607': { member: 'Nydia Velazquez', party: 'D', state: 'New York', district: '07' },
  '3608': { member: 'Hakeem Jeffries', party: 'D', state: 'New York', district: '08' },
  '3609': { member: 'Yvette Clarke', party: 'D', state: 'New York', district: '09' },
  '3610': { member: 'Daniel Goldman', party: 'D', state: 'New York', district: '10' },
  '3611': { member: 'Nicole Malliotakis', party: 'R', state: 'New York', district: '11' },
  '3612': { member: 'Jerrold Nadler', party: 'D', state: 'New York', district: '12' },
  '3613': { member: 'Adriano Espaillat', party: 'D', state: 'New York', district: '13' },
  '3614': { member: 'Alexandria Ocasio-Cortez', party: 'D', state: 'New York', district: '14' },
  '3615': { member: 'Ritchie Torres', party: 'D', state: 'New York', district: '15' },
  '3616': { member: 'George Latimer', party: 'D', state: 'New York', district: '16' },
  '3617': { member: 'Michael Lawler', party: 'R', state: 'New York', district: '17' },
  '3618': { member: 'Patrick Ryan', party: 'D', state: 'New York', district: '18' },
  '3619': { member: 'Josh Riley', party: 'D', state: 'New York', district: '19' },
  '3620': { member: 'Paul Tonko', party: 'D', state: 'New York', district: '20' },
  '3621': { member: 'Elise Stefanik', party: 'R', state: 'New York', district: '21' },
  '3622': { member: 'John Mannion', party: 'D', state: 'New York', district: '22' },
  '3623': { member: 'Nicholas Langworthy', party: 'R', state: 'New York', district: '23' },
  '3624': { member: 'Claudia Tenney', party: 'R', state: 'New York', district: '24' },
  '3625': { member: 'Joseph Morelle', party: 'D', state: 'New York', district: '25' },
  '3626': { member: 'Timothy Kennedy', party: 'D', state: 'New York', district: '26' },
  '3701': { member: 'Donald Davis', party: 'D', state: 'North Carolina', district: '01' },
  '3702': { member: 'Deborah Ross', party: 'D', state: 'North Carolina', district: '02' },
  '3703': { member: 'Gregory Murphy', party: 'R', state: 'North Carolina', district: '03' },
  '3704': { member: 'Valerie Foushee', party: 'D', state: 'North Carolina', district: '04' },
  '3705': { member: 'Virginia Foxx', party: 'R', state: 'North Carolina', district: '05' },
  '3706': { member: 'Addison McDowell', party: 'R', state: 'North Carolina', district: '06' },
  '3707': { member: 'David Rouzer', party: 'R', state: 'North Carolina', district: '07' },
  '3708': { member: 'Mark Harris', party: 'R', state: 'North Carolina', district: '08' },
  '3709': { member: 'Richard Hudson', party: 'R', state: 'North Carolina', district: '09' },
  '3710': { member: 'Pat Harrigan', party: 'R', state: 'North Carolina', district: '10' },
  '3711': { member: 'Chuck Edwards', party: 'R', state: 'North Carolina', district: '11' },
  '3712': { member: 'Alma Adams', party: 'D', state: 'North Carolina', district: '12' },
  '3713': { member: 'Brad Knott', party: 'R', state: 'North Carolina', district: '13' },
  '3714': { member: 'Tim Moore', party: 'R', state: 'North Carolina', district: '14' },
  '3800': { member: 'Julie Fedorchak', party: 'R', state: 'North Dakota', district: '00' },
  '3901': { member: 'Greg Landsman', party: 'D', state: 'Ohio', district: '01' },
  '3902': { member: 'David Taylor', party: 'R', state: 'Ohio', district: '02' },
  '3903': { member: 'Joyce Beatty', party: 'D', state: 'Ohio', district: '03' },
  '3904': { member: 'Jim Jordan', party: 'R', state: 'Ohio', district: '04' },
  '3905': { member: 'Robert Latta', party: 'R', state: 'Ohio', district: '05' },
  '3906': { member: 'Michael Rulli', party: 'R', state: 'Ohio', district: '06' },
  '3907': { member: 'Max Miller', party: 'R', state: 'Ohio', district: '07' },
  '3908': { member: 'Warren Davidson', party: 'R', state: 'Ohio', district: '08' },
  '3909': { member: 'Marcy Kaptur', party: 'D', state: 'Ohio', district: '09' },
  '3910': { member: 'Michael Turner', party: 'R', state: 'Ohio', district: '10' },
  '3911': { member: 'Shontel Brown', party: 'D', state: 'Ohio', district: '11' },
  '3912': { member: 'Troy Balderson', party: 'R', state: 'Ohio', district: '12' },
  '3913': { member: 'Emilia Sykes', party: 'D', state: 'Ohio', district: '13' },
  '3914': { member: 'David Joyce', party: 'R', state: 'Ohio', district: '14' },
  '3915': { member: 'Mike Carey', party: 'R', state: 'Ohio', district: '15' },
  '4001': { member: 'Kevin Hern', party: 'R', state: 'Oklahoma', district: '01' },
  '4002': { member: 'Josh Brecheen', party: 'R', state: 'Oklahoma', district: '02' },
  '4003': { member: 'Frank Lucas', party: 'R', state: 'Oklahoma', district: '03' },
  '4004': { member: 'Tom Cole', party: 'R', state: 'Oklahoma', district: '04' },
  '4005': { member: 'Stephanie Bice', party: 'R', state: 'Oklahoma', district: '05' },
  '4101': { member: 'Suzanne Bonamici', party: 'D', state: 'Oregon', district: '01' },
  '4102': { member: 'Cliff Bentz', party: 'R', state: 'Oregon', district: '02' },
  '4103': { member: 'Maxine Dexter', party: 'D', state: 'Oregon', district: '03' },
  '4104': { member: 'Val Hoyle', party: 'D', state: 'Oregon', district: '04' },
  '4105': { member: 'Janelle Bynum', party: 'D', state: 'Oregon', district: '05' },
  '4106': { member: 'Andrea Salinas', party: 'D', state: 'Oregon', district: '06' },
  '4201': { member: 'Brian Fitzpatrick', party: 'R', state: 'Pennsylvania', district: '01' },
  '4202': { member: 'Brendan Boyle', party: 'D', state: 'Pennsylvania', district: '02' },
  '4203': { member: 'Dwight Evans', party: 'D', state: 'Pennsylvania', district: '03' },
  '4204': { member: 'Madeleine Dean', party: 'D', state: 'Pennsylvania', district: '04' },
  '4205': { member: 'Mary Gay Scanlon', party: 'D', state: 'Pennsylvania', district: '05' },
  '4206': { member: 'Chrissy Houlahan', party: 'D', state: 'Pennsylvania', district: '06' },
  '4207': { member: 'Ryan Mackenzie', party: 'R', state: 'Pennsylvania', district: '07' },
  '4208': { member: 'Robert Bresnahan', party: 'R', state: 'Pennsylvania', district: '08' },
  '4209': { member: 'Daniel Meuser', party: 'R', state: 'Pennsylvania', district: '09' },
  '4210': { member: 'Scott Perry', party: 'R', state: 'Pennsylvania', district: '10' },
  '4211': { member: 'Lloyd Smucker', party: 'R', state: 'Pennsylvania', district: '11' },
  '4212': { member: 'Summer Lee', party: 'D', state: 'Pennsylvania', district: '12' },
  '4213': { member: 'John Joyce', party: 'R', state: 'Pennsylvania', district: '13' },
  '4214': { member: 'Guy Reschenthaler', party: 'R', state: 'Pennsylvania', district: '14' },
  '4215': { member: 'Glenn Thompson', party: 'R', state: 'Pennsylvania', district: '15' },
  '4216': { member: 'Mike Kelly', party: 'R', state: 'Pennsylvania', district: '16' },
  '4217': { member: 'Christopher Deluzio', party: 'D', state: 'Pennsylvania', district: '17' },
  '4401': { member: 'Gabe Amo', party: 'D', state: 'Rhode Island', district: '01' },
  '4402': { member: 'Seth Magaziner', party: 'D', state: 'Rhode Island', district: '02' },
  '4501': { member: 'Nancy Mace', party: 'R', state: 'South Carolina', district: '01' },
  '4502': { member: 'Joe Wilson', party: 'R', state: 'South Carolina', district: '02' },
  '4503': { member: 'Sheri Biggs', party: 'R', state: 'South Carolina', district: '03' },
  '4504': { member: 'William Timmons', party: 'R', state: 'South Carolina', district: '04' },
  '4505': { member: 'Ralph Norman', party: 'R', state: 'South Carolina', district: '05' },
  '4506': { member: 'James Clyburn', party: 'D', state: 'South Carolina', district: '06' },
  '4507': { member: 'Russell Fry', party: 'R', state: 'South Carolina', district: '07' },
  '4600': { member: 'Dusty Johnson', party: 'R', state: 'South Dakota', district: '00' },
  '4701': { member: 'Diana Harshbarger', party: 'R', state: 'Tennessee', district: '01' },
  '4702': { member: 'Tim Burchett', party: 'R', state: 'Tennessee', district: '02' },
  '4703': { member: 'Charles Fleischmann', party: 'R', state: 'Tennessee', district: '03' },
  '4704': { member: 'Scott DesJarlais', party: 'R', state: 'Tennessee', district: '04' },
  '4705': { member: 'Andrew Ogles', party: 'R', state: 'Tennessee', district: '05' },
  '4706': { member: 'John Rose', party: 'R', state: 'Tennessee', district: '06' },
  '4707': { member: 'Vacant', party: 'I', state: 'Tennessee', district: '07' },
  '4708': { member: 'David Kustoff', party: 'R', state: 'Tennessee', district: '08' },
  '4709': { member: 'Steve Cohen', party: 'D', state: 'Tennessee', district: '09' },
  '4801': { member: 'Nathaniel Moran', party: 'R', state: 'Texas', district: '01' },
  '4802': { member: 'Dan Crenshaw', party: 'R', state: 'Texas', district: '02' },
  '4803': { member: 'Keith Self', party: 'R', state: 'Texas', district: '03' },
  '4804': { member: 'Pat Fallon', party: 'R', state: 'Texas', district: '04' },
  '4805': { member: 'Lance Gooden', party: 'R', state: 'Texas', district: '05' },
  '4806': { member: 'Jake Ellzey', party: 'R', state: 'Texas', district: '06' },
  '4807': { member: 'Lizzie Fletcher', party: 'D', state: 'Texas', district: '07' },
  '4808': { member: 'Morgan Luttrell', party: 'R', state: 'Texas', district: '08' },
  '4809': { member: 'Al Green', party: 'D', state: 'Texas', district: '09' },
  '4810': { member: 'Michael McCaul', party: 'R', state: 'Texas', district: '10' },
  '4811': { member: 'August Pfluger', party: 'R', state: 'Texas', district: '11' },
  '4812': { member: 'Craig Goldman', party: 'R', state: 'Texas', district: '12' },
  '4813': { member: 'Ronny Jackson', party: 'R', state: 'Texas', district: '13' },
  '4814': { member: 'Randy Weber', party: 'R', state: 'Texas', district: '14' },
  '4815': { member: 'Monica De La Cruz', party: 'R', state: 'Texas', district: '15' },
  '4816': { member: 'Veronica Escobar', party: 'D', state: 'Texas', district: '16' },
  '4817': { member: 'Pete Sessions', party: 'R', state: 'Texas', district: '17' },
  '4818': { member: 'Vacant', party: 'I', state: 'Texas', district: '18' },
  '4819': { member: 'Jodey Arrington', party: 'R', state: 'Texas', district: '19' },
  '4820': { member: 'Joaquin Castro', party: 'D', state: 'Texas', district: '20' },
  '4821': { member: 'Chip Roy', party: 'R', state: 'Texas', district: '21' },
  '4822': { member: 'Troy Nehls', party: 'R', state: 'Texas', district: '22' },
  '4823': { member: 'Tony Gonzales', party: 'R', state: 'Texas', district: '23' },
  '4824': { member: 'Beth Van Duyne', party: 'R', state: 'Texas', district: '24' },
  '4825': { member: 'Roger Williams', party: 'R', state: 'Texas', district: '25' },
  '4826': { member: 'Brandon Gill', party: 'R', state: 'Texas', district: '26' },
  '4827': { member: 'Michael Cloud', party: 'R', state: 'Texas', district: '27' },
  '4828': { member: 'Henry Cuellar', party: 'D', state: 'Texas', district: '28' },
  '4829': { member: 'Sylvia Garcia', party: 'D', state: 'Texas', district: '29' },
  '4830': { member: 'Jasmine Crockett', party: 'D', state: 'Texas', district: '30' },
  '4831': { member: 'John Carter', party: 'R', state: 'Texas', district: '31' },
  '4832': { member: 'Julie Johnson', party: 'D', state: 'Texas', district: '32' },
  '4833': { member: 'Marc Veasey', party: 'D', state: 'Texas', district: '33' },
  '4834': { member: 'Vicente Gonzalez', party: 'D', state: 'Texas', district: '34' },
  '4835': { member: 'Greg Casar', party: 'D', state: 'Texas', district: '35' },
  '4836': { member: 'Brian Babin', party: 'R', state: 'Texas', district: '36' },
  '4837': { member: 'Lloyd Doggett', party: 'D', state: 'Texas', district: '37' },
  '4838': { member: 'Wesley Hunt', party: 'R', state: 'Texas', district: '38' },
  '4901': { member: 'Blake Moore', party: 'R', state: 'Utah', district: '01' },
  '4902': { member: 'Celeste Maloy', party: 'R', state: 'Utah', district: '02' },
  '4903': { member: 'Mike Kennedy', party: 'R', state: 'Utah', district: '03' },
  '4904': { member: 'Burgess Owens', party: 'R', state: 'Utah', district: '04' },
  '5000': { member: 'Becca Balint', party: 'D', state: 'Vermont', district: '00' },
  '5101': { member: 'Robert Wittman', party: 'R', state: 'Virginia', district: '01' },
  '5102': { member: 'Jennifer Kiggans', party: 'R', state: 'Virginia', district: '02' },
  '5103': { member: 'Robert Scott', party: 'D', state: 'Virginia', district: '03' },
  '5104': { member: 'Jennifer McClellan', party: 'D', state: 'Virginia', district: '04' },
  '5105': { member: 'John McGuire', party: 'R', state: 'Virginia', district: '05' },
  '5106': { member: 'Ben Cline', party: 'R', state: 'Virginia', district: '06' },
  '5107': { member: 'Eugene Vindman', party: 'D', state: 'Virginia', district: '07' },
  '5108': { member: 'Donald Beyer', party: 'D', state: 'Virginia', district: '08' },
  '5109': { member: 'H. Griffith', party: 'R', state: 'Virginia', district: '09' },
  '5110': { member: 'Suhas Subramanyam', party: 'D', state: 'Virginia', district: '10' },
  '5111': { member: 'James Walkinshaw', party: 'D', state: 'Virginia', district: '11' },
  '5301': { member: 'Suzan DelBene', party: 'D', state: 'Washington', district: '01' },
  '5302': { member: 'Rick Larsen', party: 'D', state: 'Washington', district: '02' },
  '5303': { member: 'Marie Perez', party: 'D', state: 'Washington', district: '03' },
  '5304': { member: 'Dan Newhouse', party: 'R', state: 'Washington', district: '04' },
  '5305': { member: 'Michael Baumgartner', party: 'R', state: 'Washington', district: '05' },
  '5306': { member: 'Emily Randall', party: 'D', state: 'Washington', district: '06' },
  '5307': { member: 'Pramila Jayapal', party: 'D', state: 'Washington', district: '07' },
  '5308': { member: 'Kim Schrier', party: 'D', state: 'Washington', district: '08' },
  '5309': { member: 'Adam Smith', party: 'D', state: 'Washington', district: '09' },
  '5310': { member: 'Marilyn Strickland', party: 'D', state: 'Washington', district: '10' },
  '5401': { member: 'Carol Miller', party: 'R', state: 'West Virginia', district: '01' },
  '5402': { member: 'Riley Moore', party: 'R', state: 'West Virginia', district: '02' },
  '5501': { member: 'Bryan Steil', party: 'R', state: 'Wisconsin', district: '01' },
  '5502': { member: 'Mark Pocan', party: 'D', state: 'Wisconsin', district: '02' },
  '5503': { member: 'Derrick Van Orden', party: 'R', state: 'Wisconsin', district: '03' },
  '5504': { member: 'Gwen Moore', party: 'D', state: 'Wisconsin', district: '04' },
  '5505': { member: 'Scott Fitzgerald', party: 'R', state: 'Wisconsin', district: '05' },
  '5506': { member: 'Glenn Grothman', party: 'R', state: 'Wisconsin', district: '06' },
  '5507': { member: 'Thomas Tiffany', party: 'R', state: 'Wisconsin', district: '07' },
  '5508': { member: 'Tony Wied', party: 'R', state: 'Wisconsin', district: '08' },
  '5600': { member: 'Harriet Hageman', party: 'R', state: 'Wyoming', district: '00' },
  '6098': { member: 'Aumua Amata Radewagen', party: 'R', state: 'American Samoa', district: '98' },
  '6698': { member: 'James Moylan', party: 'R', state: 'Guam', district: '98' },
  '6998': { member: 'Kimberlyn King-Hinds', party: 'R', state: 'Commonwealth of the Northern Mariana Islands', district: '98' },
  '7298': { member: 'Pablo Hernandez', party: 'D', state: 'Puerto Rico', district: '98' },
  '7898': { member: 'Stacey Plaskett', party: 'D', state: 'United States Virgin Islands', district: '98' },
};
